[package]
name = "emosaic"
version = "0.1.0"
authors = ["Will Dady <willdady@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.0"
clap = "2.33.0"
