#!/bin/bash

# Generate .env.{environment} file from CloudFormation stack outputs
# Usage: ./generate-env.sh [environment] [region]

ENVIRONMENT=${1:-${ENVIRONMENT:-prod}}
AWS_REGION=${2:-${AWS_REGION:-eu-west-3}}
ENV_FILE=".env.${ENVIRONMENT}"

echo "Generating $ENV_FILE for environment: $ENVIRONMENT (region: $AWS_REGION)"

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found"
    exit 1
fi

# Get values from CloudFormation
USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name ${ENVIRONMENT}-mosaic-infrastructure \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
    --output text --region $AWS_REGION 2>/dev/null)

if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" = "None" ]; then
    echo "❌ Could not get UserPoolId. Is ${ENVIRONMENT}-mosaic-infrastructure deployed?"
    exit 1
fi

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name ${ENVIRONMENT}-mosaic-infrastructure \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
    --output text --region $AWS_REGION)

API_URL=$(aws cloudformation describe-stacks \
    --stack-name ${ENVIRONMENT}-tile-flags-infrastructure \
    --query "Stacks[0].Outputs[?OutputKey=='APIGatewayURL'].OutputValue" \
    --output text --region $AWS_REGION)

# Write environment-specific .env file
cat > "$ENV_FILE" << EOF
# Generated by generate-env.sh on $(date)
# Environment: $ENVIRONMENT | Region: $AWS_REGION

# AWS Cognito Configuration
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_AWS_REGION=$AWS_REGION

# API Configuration
VITE_API_URL=$API_URL
EOF

echo "✅ Generated $ENV_FILE:"
cat "$ENV_FILE"
